### ISSUE TITLE
README shows package information not aligned 

### ISSUE THREAD

**Issue by Curt-Park** [dongminlee94/meta-learning-for-everyone#107]
## Describe the bug
README shows package information not aligned.

<img width="805" alt="스크린샷 2022-10-06 오후 9 02 15" src="https://user-images.githubusercontent.com/14961526/194307596-fde1bd61-5429-440e-ada7-7082eaa1364e.png">

- no package information about `PyTorch` in both `requirements.txt` and `setup.py`.
- no mypy setting

**Comment by dongminlee94** [comment]
- no package information about PyTorch in both requirements.txt and setup.py. --> PyTorch is installed by [download-torch.py](https://github.com/dongminlee94/meta-learning-for-everyone/blob/main/scripts/download-torch.py) because we support installation in multiple os envs.
- no mypy setting --> done. many thanks!
